/**:
  ros__parameters:
    # --- 基本設定 ---
    speed_scale: 1.0
    steer_scale: 1.0
    timer_hz: 40.0

    # --- モード切替ボタン ---
    joy_button_index: 2        # △ボタンで手動モード
    ack_button_index: 3        # □ボタンで自律モード

    # --- start/stop トリガボタン ---
    start_button_index: 7      # R2 ボタンで start=true
    stop_button_index: 6       # L2  ボタンで start=false

    # --- 反転設定 ---
    invert_speed: true
    invert_steer: false

    # --- オフセット調整 ---
    initial_speed_offset: 0.0
    initial_steer_offset: 0.14
    offset_increment: 0.01
    max_steer_offset: 0.3
    min_steer_offset: -0.3
    max_speed_offset: 1.0
    min_speed_offset: -1.0


## button index (DualShock4) humble
## humble humble humble
# 0: □
# 1: ×
# 2: ○
# 3: △
# 4: L1
# 5: R1
# 6: L2
# 7: R2
# 8: share
# 9: option
# 10: home
# 11: L3
# 12: R3

## axes index (DualShock4) for D-pad（オフセット調整用）
# →: axes[6] == -1.0  → steer_offset +
# ←: axes[6] ==  1.0  → steer_offset –
# ↑: axes[7] ==  1.0  → speed_offset +
# ↓: axes[7] == -1.0  → speed_offset –


## button index (DualShock4) foxy
# 0: ×
# 1: ○
# 2: △
# 3: □
# 4: L1
# 5: R1
# 6: L2
# 7: R2
# 8: share
# 9: option
# 10: home
# 11: L3
# 12: R3

## axes index (DualShock4) for D-pad（オフセット調整用）
# →: axes[6] == -1.0  → steer_offset +
# ←: axes[6] ==  1.0  → steer_offset –
# ↑: axes[7] ==  1.0  → speed_offset +
# ↓: axes[7] == -1.0  → speed_offset –
