/**:
  ros__parameters:
    speed_scale: 1.0
    timer_hz: 40.0
    joy_button_index: 2
    ack_button_index: 3

    stop_axis_index: 6
    stop_axis_value: 1.0
    start_axis_index: 6
    start_axis_value: -1.0

    invert_speed: false
    invert_steer: false

    increase_steer_button_index: 7
    decrease_steer_button_index: 6
    max_steer_offset: 0.2
    min_steer_offset: 0.0
    offset_increment: 0.01

## button index (dual shock 4)
# 0: ×
# 1: ○
# 2: △
# 3: □
# 4: L1
# 5: R1
# 6: L2
# 7: R2
# 8: share
# 9: option
# 10: home
# 11: L3
# 12: R3

## axes index (dual shock 4)
# →: axes 6 == -1.0
# ←: axes 6 == 1.0
# ↑: axes 7 == 1.0
# ↓: axes 7 == -1.0
